### ISSUE TITLE
Output as standard metrics

### ISSUE THREAD

**Issue by mhf-ir** [akme/get-closer#6]
**Is your feature request related to a problem? Please describe.**
Find out infrastructure wan status via metrics.

**Describe the solution you'd like**
Output metrics to telegraf and Prometheus.

**Describe alternatives you've considered**
Handle by my self.

**Additional context**
Get metrics of datacenters wan and internet access is one of the checkpoint of find out network/datacenter problems.

**Comment by akme** [comment]
Could you please provide an example of such an output?

**Comment by mhf-ir** [comment]
Consider wan network:
```
server s1 155.155.155.1, datacenter d1 
server s2 156.156.156.1, datacenter d2 
server s3 157.157.157.1, datacenter d3 
```
Metrics from server s3 (data center 3) closest to (s1 and s2) could be send to telegraf (then influxdb) for long time archive, then we can know state of network for future decision.

**Comment by akme** [comment]
I still didn't get it, what format of data do you need and how you will push them to telegraf?

**Comment by mhf-ir** [comment]
when telegraf is running on server s3

```toml
[[inputs.get_closer]]
   servers = ["s1", "s2"]
```
Via http endpoints or any methods:

```
get_closer,server="s1",time=12i,closer=false 1400000000000000000
get_closer,server="s2",time=5i,closer=true 1400000000000000000
```

Each insert per server for speed also with that special time we know closer one on s3 server.

**Comment by akme** [comment]
http endpoint isn't an option for such simple script, json output is planned, so you can parse data with ease and push it to any aggregator you need
